kind: pipeline
type: docker
name: Build S2I spring-boot images

steps:
- name: docker build adoptopenjdk/openjdk8:alpine
  image: plugins/docker
  settings:
    repo: springboot-java
#    registry: artifactory.witcom.services
    dockerfile: base/alpine/Dockerfile
    context: ./base/alpine
    dry_run: true
    tags:
      - jdk8
    build_args:
      - BASE_IMAGE=adoptopenjdk/openjdk8:alpine
- name: docker build adoptopenjdk/openjdk11:alpine
  image: plugins/docker
  settings:
    repo: springboot-java
#    registry: artifactory.witcom.services
    dockerfile: base/alpine/Dockerfile
    context: ./base/alpine
    dry_run: true
    tags:
      - jdk11
    build_args:
      - BASE_IMAGE=adoptopenjdk/openjdk11:alpine

#  when:
#    branch:
#    - main
